### ISSUE TITLE
improvement: error handling of arrays in functions

### ISSUE THREAD

**Issue by denverbaumgartner** [RubiconDeFi/rubi-py#13]
to keep a running list of potential improvements: 
- [] `rubi/rubi/contracts/aid.py` functions that  involve passing in array values 
- [] a lot of other places in the repo...

**Comment by adamamsmith** [comment]
Closed by #26 

This PR establishes a pattern of passing objects to the instead of bare arrays. This means that malformed arrays can no longer be passed to the underlying contracts (unless the user really wants to interact with them directly).
