### ISSUE TITLE
improvement: create web3 object for user

### ISSUE THREAD

**Issue by denverbaumgartner** [RubiconDeFi/rubi-py#16]
**today:** we require the user to pass in a web3 object in order to create the Rubicon class. we should just ask the user to input an endpoint instead. input is error

**:soon:** we will allow the rubi class, and possibly other contract classes(?), to be created just from a node endpoint. we should determine if the connection is HTTP or WS. in the future, we should have WS-specific functionality that is enabled.

**Comment by adamamsmith** [comment]
https://github.com/RubiconDeFi/rubi-py/pull/26 begins to deal with this but does not add support for WS

**Comment by denverbaumgartner** [comment]
> #26 begins to deal with this but does not add support for WS

sounds good, i think we just close out this issue when we resolve web3 object handling for the user and open a separate issue for ws-specific functionality after this initial v2 migration is complete.

**Comment by adamamsmith** [comment]
Closed by #26
