### ISSUE TITLE
bug: event poller stops working

### ISSUE THREAD

**Issue by perryascott** [RubiconDeFi/rubi-py#52]
I am experiencing an issue with the start_event_poller stopping after extended usage.

Replicating this is difficult, as the problem usually happens at a somewhat random interval, but the behavior usually goes something like this:
1. Call the start_event_poller() it begins working for some time
2. A transaction error occurs (insufficient funds, gas, exceeding allowance)
3. The event poller then stops working

Replicate:
```
# Here is the exact way I'm initializing the event poller
# The problem is not local to a certain pair type
# problem occured on versions 2.0.5 and 2.0.6
    client.start_event_poller(pair_string, event_type=EmitOfferEvent, filters={"maker": client.wallet}, poll_time=poll_time)
    client.start_event_poller(pair_string, event_type=EmitTakeEvent, filters={"maker": client.wallet}, poll_time=poll_time)
    client.start_event_poller(pair_string, event_type=EmitCancelEvent, filters={"maker": client.wallet}, poll_time=poll_time)
    client.start_event_poller(pair_string, event_type=EmitDeleteEvent, filters={"maker": client.wallet}, poll_time=poll_time)
```

Let me know if there is any other info I can provide to help.

**Comment by perryascott** [comment]
Hey @adamamsmith,

Thanks for looking into this for me. I haven't been seeing this issue as of lately and also have had a hard time duplicating this. If I don't see the error occur again within the next couple of days I will close the issue.

**Comment by adamamsmith** [comment]
Great to hear you are no longer experiencing the issue. I did experience the same issue before you opened the ticket however I had also already pushed a fix by the time you opened it. I was concerned I had missed an edge case however if you are no longer experiencing it that is great 👍 

I'm going to close the issue @perryascott but please reopen it if you do notice it again 👍
