### ISSUE TITLE
improvement: transaction building -> maxFeePerGas and maxPriorityFeePerGas

### ISSUE THREAD

**Issue by denverbaumgartner** [RubiconDeFi/rubi-py#7]
**today:** we are signing transactions utilizing `gas` and `gasPrice`. this is a dated method because of the London upgrade and should be updated.

**soon:** we should sign transactions utilizing `maxFeePerGas` and `maxPriorityFeePerGas`. this is also a mere matter of what worked today, but will be improved upon very 🔜 📈

**Comment by adamamsmith** [comment]
Closed by #26
