### ISSUE TITLE
enhancement: Receive more information regarding the offers from the TransactionReceipt

### ISSUE THREAD

**Issue by soheiyagi** [RubiconDeFi/rubi-py#79]
I am placing an order with rubi-py, but currently TransactionReceipt does not return information such as whether my order was confirmed or failed.

It seems that there is no other rubi-py method, so currently there is no choice but to get information from the subgraph, but I think it would be good to be able to complete it with rubi-py as much as possible when launching a small bot.

I'm not sure if it's better to implement it with another rubi-py method or add it to TransactionReceipt.

Thanks for developing!

**Comment by denverbaumgartner** [comment]
@soheiyagi thanks so much for opening this issue! with many transactions, there are a lot of `logs` returned that contain relevant, and irrelevant, information. to start, it sounds like the most useful piece of information that we could return back would be the `emitOffer` logs, which contain all relevant detail to an order. additionally, we should probably make sure to include any `emitTake` information to cover scenarios where a user's orders are matching.

personally, i do think it makes the most sense to expose this information through the `TransactionReceipt` as this reduces the need to place any additional calls. however, we could simply provide a function such as `parse_transaction_receipt` that would allow you to pass in the `TransactionReceipt` and return all relevant `logs`. 

i still lean towards the former approach, would love to know @adamamsmith thoughts on the matter

**Comment by adamamsmith** [comment]
Totally agree with you @denverbaumgartner. Will look into implementing this as I think it's a very beneficial change for all users of rubi-py 👍
