### ISSUE TITLE
improvement: get_log_xyz_hash

### ISSUE THREAD

**Issue by denverbaumgartner** [RubiconDeFi/rubi-py#8]
**today:** throughout the repository almost every contract class has a function called get_log_xyz_hash that returns an event signature. today these values are hardcoded. 

**soon:** it would be great if these values were generated from the contract .sol files upon initialization of the class, or even within rolodex.py

**Comment by adamamsmith** [comment]
Closed by #26 

This PR meant these no longer have to be hardcoded however they are still fetched from the abis stored in the repo. However https://github.com/RubiconDeFi/rubi-py/issues/2 already mentions this.
