### ISSUE TITLE
bug: client.get_orderbook

### ISSUE THREAD

**Issue by denverbaumgartner** [RubiconDeFi/rubi-py#84]
from a bug report submitted by @soheiyagi in the public discord

occasionally, when attempting to construct an `OrderBook` object, when building the `BookSide` using `from_rubicon_offers` we encounter an `IndexError` such as follows: 

`if levels and levels[-i].price == price:... IndexError: list index out of range`

looking into this function it appears that we should be utilizing `levels[-1]` instead of `levels[-i]`. i believe the issue we are encountering is a result of offers existing at the same level of the book, which only occasionally happens. furthermore, i believe we need to sort the `offers` based on price if we want to use this current approach in order to correctly place multiple offers within the same `BookLevel`. alternatively, we could utilize a dictionary such as is done [here](https://github.com/RubiconDeFi/rubi-py/blob/49abf6a6f9b25eb0028a1d11c79593f0ef73ac66/rubi/rubi/rubicon_types/orderbook.py#L330) to keep track of price and at which level an offer should be inserted.

i may be misinterpreting something here, would love to know your thoughts @adamamsmith 🙏

**Comment by adamamsmith** [comment]
@denverbaumgartner I had a look and yes this is a bug. Have put in a quick MR to fix this.

Now to comment on the alternative of constructing a dictionary to store the offers at each level.

My opinion is that there is no reason to do this. Why would a user care about the specific orders at each level in an order book? I am open to being disagreed with but I can't think of a reason that this is particularly useful.

As long as the user has:

1. A full representation of the orderbook
2. A full representation of their own offers.

I don't think they need further information about the other offers that build up the orderbook. 

As such, I don't think it is useful to construct and manage a dictionary of offers at each level. Hence merging the offers into one level if they have the same price. But let me know if you disagree @denverbaumgartner and then we can iterate from there. 

Also would love any opinions from our users on this. It would be great if we could run a poll or something for people using `rubi-py`. Not sure if this is possible and definitely tangential to this issue.
